//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_id { get; set; }
        public string contact_phone { get; set; }
        public string contact_email { get; set; }
        public string contact_address { get; set; }
        public string contact_work_time { get; set; }
        public string contact_facebook { get; set; }
        public string contact_intagram { get; set; }
        public string contact_twitter { get; set; }
        public string contact_google { get; set; }
    }
}
