//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int galery_id { get; set; }
        public Nullable<int> galery_user_id { get; set; }
        public string img_src { get; set; }
        public string galery_comment { get; set; }
    
        public virtual User User { get; set; }
    }
}
