//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelEntities : DbContext
    {
        public TravelEntities()
            : base("name=TravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Navbar> Navbars { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Travel_Type> Travel_Type { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Tra> Tras { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Postt> Postts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Join> Joins { get; set; }
    }
}
