//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Type
    {
        public int t_type_id { get; set; }
        public string t_ttype_name { get; set; }
    
        public virtual Travel_Type Travel_Type1 { get; set; }
        public virtual Travel_Type Travel_Type2 { get; set; }
    }
}
